name: Google App Engine Deployment
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieving the repo
        uses: actions/checkout@v1
      - name: Setting up GCloud Auth
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        env:
          APPLICATION_CREDENTIALS: ${{ secrets.APPLICATION_CREDENTIALS }}
        run: |
          echo $APPLICATION_CREDENTIALS > ~/service_account_credentials.json
          pip install pytest
          python -m pytest test/
      - name: Run deployment
        if: success()
        uses: actions/gcloud/cli@master
        env:
          CLOUDSDK_CORE_PROJECT: kanyai
        with:
          entrypoint: gcloud
          args: app deploy ./app.yaml --quiet
